### ISSUE TITLE
Intelligent subheading management

### ISSUE THREAD

**Issue by alexroan** [ChainAccelOrg/trello_to_audit_report#8]
The tool copies the .md file verbatim. Could it be more intelligent about the number of hashes (#) before subheadings? The image below shows many `##` headings, but there should be `###` subheadings for items under the main ticket title.
<img width="211" alt="Screenshot 2023-03-27 at 20 26 30" src="https://user-images.githubusercontent.com/6523673/228290239-aca1ba1a-a2e1-49d9-9e68-97010aa8aef9.png">

**Comment by PatrickAlphaC** [comment]
Fixed in: https://github.com/ChainAccelOrg/trello_to_audit_report/pull/10
